### ISSUE TITLE
Is ubuntu 18.04 still supported?

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [amanusk/s-tui#137]
I upgraded some hardware opened it and saw it still works, sweet wonder if there are any updates, yep..
I just updated it cleared my old configs and get a error:
```
me@Z97Killer:~/Downloads/s-tui$ python -m s_tui.s_tui
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/chad/Downloads/s-tui/s_tui/s_tui.py", line 927, in <module>
    main()
  File "/home/chad/Downloads/s-tui/s_tui/s_tui.py", line 881, in main
    graph_controller = GraphController(args)
  File "/home/chad/Downloads/s-tui/s_tui/s_tui.py", line 698, in __init__
    possible_sources = self._load_config(args.t_thresh)
  File "/home/chad/Downloads/s-tui/s_tui/s_tui.py", line 631, in _load_config
    FreqSource(),
  File "s_tui/sources/freq_source.py", line 49, in __init__
    self.top_freq = psutil.cpu_freq().max
AttributeError: 'NoneType' object has no attribute 'max'
me@Z97Killer:~/Downloads/s-tui$ python3 -m s_tui.s_tui
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chad/Downloads/s-tui/s_tui/s_tui.py", line 38, in <module>
    import urwid
ModuleNotFoundError: No module named 'urwid'
```
I need to update my system name...
not sure if i should bed using python 2 or 3, urwid is installed at least for python2, not sure how it install it for python3

**Comment by amanusk** [comment]
You can install it with `pip3 install urwid` 
Similarly for `psutil`

**Comment by GM-Script-Writer-62850** [comment]
got it working in python3, thanks

**Comment by amanusk** [comment]
Great. Please update on compatibility issues. Closing
