### ISSUE TITLE
Broken package installation on openSUSE Leap 15.5 due to requirement of python3-psutil version >= 5.9.1

### ISSUE THREAD

**Issue by cristianst85** [amanusk/s-tui#209]
Hi. I am not sure where exactly to report this, but it appears to be a package problem.

### Step 1: Describe your environment

  * System (Intel/AMD/Raspberry Pi etc): Intel
  * OS version: openSUSE Leap 15.5
  * s-tui version: 1.1.4
  * Installation method(pip/PPA/source code): zypper
  * Package: s-tui-1.1.4-bp155.1.5.noarch.rpm
  
#### Observed Results:

When attempting to run `s-tui` it crashes with:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (psutil 5.8.0 (/usr/lib64/python3.6/site-packages), Requirement.parse('psutil>=5.9.1'), {'s-tui'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/s-tui", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psutil>=5.9.1' distribution was not found and is required by s-tui 
```

#### Debug Results, output of `s-tui -d` created in a file `_s-tui.log`: 

n/a

  
#### Steps to reproduce:
1. install available package using `zypper`
2. run `s-tui`

Note: the available `python3-psutil` package version for openSUSE Leap 15.5 is `5.8.0-150300.3.3.2`.

Repos links:
* http://download.opensuse.org/distribution/leap/15.5/repo/oss/noarch/
* http://download.opensuse.org/update/leap/15.5/oss/noarch/

**Comment by cristianst85** [comment]
This is fixed now with the latest updates for openSUSE Leap 15.5. By running `zypper ref` and `zypper up` the `python3-psutil` package version is updated to `5.9.1-150300.3.6.1`.
