### ISSUE TITLE
"ImportError: No module named AboutMenu"

### ISSUE THREAD

**Issue by sanderjo** [amanusk/s-tui#35]
After my "git pull" yesterday (and also after a fresh "git clone") I get "ImportError: No module named AboutMenu". 

```
sander@haring:~/git/s-tui$ git pull
Already up-to-date.
sander@haring:~/git/s-tui$ s_tui/s_tui.py
Traceback (most recent call last):
  File "s_tui/s_tui.py", line 40, in <module>
    from s_tui.AboutMenu import AboutMenu
  File "/home/sander/git/s-tui/s_tui/s_tui.py", line 40, in <module>
    from s_tui.AboutMenu import AboutMenu
ImportError: No module named AboutMenu
sander@haring:~/git/s-tui$
```

```
sander@haring:~/git/s-tui$ cd s_tui/
sander@haring:~/git/s-tui/s_tui$ ./s_tui.py
Traceback (most recent call last):
  File "./s_tui.py", line 40, in <module>
    from s_tui.AboutMenu import AboutMenu
  File "/home/sander/git/s-tui/s_tui/s_tui.py", line 40, in <module>
    from s_tui.AboutMenu import AboutMenu
ImportError: No module named AboutMenu
```

```
sander@haring:~/git/s-tui/s_tui$ ls -al AboutMenu.py
-rw-rw-r-- 1 sander sander 1972 Sep  1 07:43 AboutMenu.py
sander@haring:~/git/s-tui/s_tui$
```

**Comment by amanusk** [comment]
I have added python3 support yesterday. This now happens when running s_tui.py directly. 
Running is still possible with `python -m s_tui.s_tui` from the main repo directory

**Comment by sanderjo** [comment]
That works. Thanks!
