### ISSUE TITLE
Latest arch update (Antergos) breaks s-tui

### ISSUE THREAD

**Issue by gerega** [amanusk/s-tui#69]
### Step 1: Describe your environment

  * System (Intel/AMD/Raspberry Pi etc): Intel
  * OS version: latest Antergos
  * s-tui version: the latest one, actually even s-tui --version doesnt start anymore
  * Installation method(pip/PPA/source code): yaourt
  
#### Observed Results:

s-tui doesnt start anymore after latest update oft Arch where many Python packages has Been updated through "pacman -Syyu"
  
#### Steps to reproduce:

Simply start s-tui

```
* Replace this with relevant code to reproduce the problem *
```
[user@file ~]$ s-tui 
Traceback (most recent call last):
  File "/usr/bin/s-tui", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 's-tui==0.7.5' distribution was not found and is required by the application
[user@file ~]$

**Comment by amanusk** [comment]
Thanks for letting me know.
I wonder if this has anything to do with upgrade to python3.7

Please update if this happens again.
